apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wh9v76mkc-nodejs 
  janus-idp.io/tekton: wh9v76mkc-nodejs
  backstage.io/kubernetes-id: wh9v76mkc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wh9v76mkc-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml