apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wh9v76mkc-nodejs-gitops
  description: This is GitOps manifest for wh9v76mkc-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=wh9v76mkc-nodejs
    backstage.io/kubernetes-id: wh9v76mkc-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wh9v76mkc-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wh9v76mkc-nodejs
