apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wh9v76mkc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wh9v76mkc-nodejs 
  name: wh9v76mkc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wh9v76mkc-nodejs 
